title = Links

[Editing]

  [[Editing.Articles]]
    title   = "xi-editor retrospective"
    author  = "Raph Levien"
    link    = "https://raphlinus.github.io/xi/2020/06/27/xi-retrospective.html"


["Community"]
  [["Community.Artiles"]]
    title   = "The Impact of Toxic Influencers on Communities"
    author  = "Erin Casali"
    link    = "https://intenseminimalism.com/2020/the-impact-of-toxic-influencers-on-communities/"


["Language Parsing"]

  [["Language Parsing".Articles]]
    title   = "Abstract vs. Concrete Syntax Trees"
    author  = "Eli Bendersky"
    link    = "https://eli.thegreenplace.net/2009/02/16/abstract-vs-concrete-syntax-trees"

  [["Language Parsing".Articles]]
    title  = "LL and LR Parsing Demystified"
    author = "Josh Haberman"
    link   = "https://blog.reverberate.org/2013/07/ll-and-lr-parsing-demystified.html"

  [["Language Parsing".Videos]]
    title   = "Tree-sitter - a new parsing system for programming tools"
    author  = "Max Brunsfeld"
    link    = "https://www.youtube.com/watch?v=Jes3bD6P0To"


[Programming]

  [[TypeScript.Articles]]
    title  = "The Disposable Pattern in TypeScript"
    author = "Henning Dieterichs"
    link   = "https://blog.hediet.de/post/the_disposable_pattern_in_typescript"

  [[Scala.Articles]]
    title  = "Make ADTs subtypes of Product and Serializable"
    author = "Nicolas Rinaudo"
    link   = "https://nrinaudo.github.io/scala-best-practices/adts/product_with_serializable.html"

  [[Scala.Videos]]
    title   = "Folding algebraic data types - Scala tutorial"
    author  = "Jakub Kozłowski"
    link    = "https://www.youtube.com/watch?v=cS4MOUsuWYc&feature=emb_title"

["Software Development"]

  [["Software Development".Articles]]
    title  = "Principles of Design"
    author = "Tim Berners-Lee"
    link   = "https://www.w3.org/DesignIssues/Principles.html"

  [["Software Development".Articles]]
    title  = "It's probably time to stop recommending Clean Code"
    author = "qntm"
    link   = "https://qntm.org/clean"

  [["Software Development".Articles]]
    title  = "The golden rule of software quality"
    author = "Gabriel Gonzalez"
    link   = "http://www.haskellforall.com/2020/07/the-golden-rule-of-software-quality.html"

  [["Software Development".Articles]]
    title  = "Towards Faster Iteration in Industrial Haskell"
    author = "Patrick Thomson"
    link   = "https://blog.sumtypeofway.com/posts/fast-iteration-with-haskell.html"

[Vim]

  [[Vim.Articles]]
    title  = "Oil and vinegar - split windows and the project drawer"
    author = "Drew Neil"
    link   = "http://vimcasts.org/blog/2013/01/oil-and-vinegar-split-windows-and-project-drawer"

  [[Vim.Articles]]
    title  = "Vim: you don't need NERDtree or (maybe) netrw"
    author = "George Ornbo"
    link   = "https://shapeshed.com/vim-netrw/"

  [[Vim.Articles]]
    title  = "Build your own Vim statusline"
    author = "George Ornbo"
    link   = "https://shapeshed.com/vim-statuslines/"
