name: Generate Chronica Site

on:
  push:
    
jobs:
  build:
    name: Chronica build and deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Get ammonite
        run: ./amm generate-wiki.sc
