name: Generate Chronica Site

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Chronica build and deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Download Ammonite
        run: |
          curl -L https://github.com/lihaoyi/ammonite/releases/download/2.1.4/2.13-2.1.4-bootstrap > amm
          chmod +x amm

      - name: Cache Coursier
        uses: actions/cache@v1
        with:
          path: ~/.cache/coursier/v1
          key: ${{ runner.os }}-linux-coursier

      - name: Generate site with Ammonite
        run: ./amm --no-remote-logging website.sc generate

      - name: Vercel Deployment
        uses: amondnet/vercel-action@v19
        with:
          vercel-token: ${{ secrets.ZEIT_TOKEN }}
          vercel-org-id: ${{ secrets.ORG_ID }}
          vercel-project-id: ${{ secrets.PROJECT_ID }}
          vercel-args: '--prod'
