name: Generate Chronica Site

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Chronica build and deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Cache Coursier
        uses: actions/cache@v1
        with:
          path: ~/.cache/coursier/v1
          key: ${{ runner.os }}-linux-coursier

      - name: Download Ammonite
        run: |
          curl -L https://github.com/lihaoyi/ammonite/releases/download/2.0.4/2.13-2.0.4-boostrap > amm
          chmod +x amm

      - name: Generate site with Ammonite
        run: ./amm website.sc

      - name: Copy over slides
        run: cp presentations/* out/

      - name: Copy over media
        run: mkdir out/media && cp media/* out/media/

      - name: Zeit Now Deployment
        uses: amondnet/now-deployment@v2.0.2
        with:
          zeit-token: ${{ secrets.ZEIT_TOKEN }}
          now-org-id: ${{ secrets.ORG_ID }}
          now-project-id: ${{ secrets.PROJECT_ID }}
          now-args: '--prod'
