name: Generate Chronica Site

on:
  push:
    branches:

jobs:
  build:
    name: Chronica build and deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1
