name: Generate Chronica Site

on:
  push:

jobs:
  build:
    name: Chronica build and deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Generate site with Ammonite
        run: ./amm generate-chronica.sc
   
      - name: Zeit Now Deployment
        uses: amondnet/now-deployment@v2.0.0 
        with:
          zeit-token: ${{ secrets.ZEIT_TOKEN }}
          now-org-id: ${{ secrets.ORG_ID }}
          now-project-id: ${{ secrets.PROJECT_ID }}
          working-directory: "out"
